{% set version = "0.9.0" %}

package:
  name: pygeoapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygeoapi/pygeoapi-{{ version }}.tar.gz
  sha256: 3e284effb54c2c8cd2673cea86d36fab8dcf36525bcb573997649efeeac4ef94

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pygeoapi=pygeoapi:cli

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - click
    - flask
    - pyproj
    - python-dateutil
    - pytz
    - pyyaml
    - rasterio
    - unicodecsv

test:
  files:
    - local.config.yml
  commands:
    - export PYGEOAPI_CONFIG=local.config.yml
    - pygeoapi --help

about:
  home: https://pygeoapi.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: pygeoapi provides an API to geospatial data

extra:
  recipe-maintainers:
    - tomkralidis
    - ocefpaf
