{% set version = "0.8.0" %}

package:
  name: pygeoapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygeoapi/pygeoapi-{{ version }}.tar.gz
  sha256: 2ce5767f193f701d8be7a8b4b576f8e6af248e23d954e09333e21e7ea781dff6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pygeoapi=pygeoapi:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - flask
    - python-dateutil
    - pytz
    - pyyaml
    - unicodecsv

test:
  files:
    - local.config.yml
  commands:
    - export PYGEOAPI_CONFIG=local.config.yml
    - pygeoapi --help

about:
  home: https://pygeoapi.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: pygeoapi provides an API to geospatial data

extra:
  recipe-maintainers:
    - tomkralidis
    - ocefpaf
